### ISSUE TITLE
Fix access to Science Server

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dblinea#23]
Corrigir os endereços do science server na biblioteca atualmente está apontando para .gov.br deveria ser .org.br

**Comment by gschwend** [comment]
@glaubervila está corrigido, certo? Posso marcar como Done?

**Comment by gschwend** [comment]
@jandsonrj: bug fix super simples para molhar os pés no science server

**Comment by rcboufleur** [comment]
@gschwend @glaubervila essa correção foi unida ao repositório principal? em main ainda consta o apontamento para gov.br

**Comment by jandsonrj** [comment]
> @gschwend @glaubervila essa correção foi unida ao repositório principal? em main ainda consta o apontamento para gov.br
@rcboufleur Foi criado um issue para resolver isso, eu inclusive já ajustei, vou abrir um PR
